COUNTRY_TO_CONTINENT = {
    # Africa (54 countries)
    "Algeria": "Africa", "Angola": "Africa", "Benin": "Africa", "Botswana": "Africa",
    "Burkina Faso": "Africa", "Burundi": "Africa", "Cameroon": "Africa", "Cape Verde": "Africa",
    "Central African Republic": "Africa", "Chad": "Africa", "Comoros": "Africa", "Congo": "Africa",
    "DR Congo": "Africa", "Djibouti": "Africa", "Egypt": "Africa", "Equatorial Guinea": "Africa",
    "Eritrea": "Africa", "Eswatini": "Africa", "Ethiopia": "Africa", "Gabon": "Africa",
    "Gambia": "Africa", "Ghana": "Africa", "Guinea": "Africa", "Guinea-Bissau": "Africa",
    "Ivory Coast": "Africa", "Kenya": "Africa", "Lesotho": "Africa", "Liberia": "Africa",
    "Libya": "Africa", "Madagascar": "Africa", "Malawi": "Africa", "Mali": "Africa",
    "Mauritania": "Africa", "Mauritius": "Africa", "Morocco": "Africa", "Mozambique": "Africa",
    "Namibia": "Africa", "Niger": "Africa", "Nigeria": "Africa", "Rwanda": "Africa",
    "São Tomé and Príncipe": "Africa", "Senegal": "Africa", "Seychelles": "Africa", "Sierra Leone": "Africa",
    "Somalia": "Africa", "South Africa": "Africa", "South Sudan": "Africa", "Sudan": "Africa",
    "Tanzania": "Africa", "Togo": "Africa", "Tunisia": "Africa", "Uganda": "Africa",
    "Zambia": "Africa", "Zimbabwe": "Africa",
    
    # Asia (47 countries)
    "Afghanistan": "Asia", "Australia": "Asia", "Bahrain": "Asia", "Bangladesh": "Asia",
    "Bhutan": "Asia", "Brunei": "Asia", "Cambodia": "Asia", "China": "Asia",
    "Chinese Taipei": "Asia", "Guam": "Asia", "Hong Kong": "Asia", "India": "Asia",
    "Indonesia": "Asia", "Iran": "Asia", "Iraq": "Asia", "Japan": "Asia",
    "Jordan": "Asia", "Kazakhstan": "Asia", "Kuwait": "Asia", "Kyrgyzstan": "Asia",
    "Laos": "Asia", "Lebanon": "Asia", "Macau": "Asia", "Malaysia": "Asia",
    "Maldives": "Asia", "Mongolia": "Asia", "Myanmar": "Asia", "Nepal": "Asia",
    "New Zealand": "Asia", "North Korea": "Asia", "Oman": "Asia", "Pakistan": "Asia",
    "Palestine": "Asia", "Philippines": "Asia", "Qatar": "Asia", "Saudi Arabia": "Asia",
    "Singapore": "Asia", "South Korea": "Asia", "Sri Lanka": "Asia", "Syria": "Asia",
    "Tajikistan": "Asia", "Thailand": "Asia", "Timor-Leste": "Asia", "Turkmenistan": "Asia",
    "United Arab Emirates": "Asia", "Uzbekistan": "Asia", "Vietnam": "Asia", "Yemen": "Asia",
    
    # Europe (55 countries)
    "Albania": "Europe", "Andorra": "Europe", "Armenia": "Europe", "Austria": "Europe",
    "Azerbaijan": "Europe", "Belarus": "Europe", "Belgium": "Europe", "Bosnia and Herzegovina": "Europe",
    "Bosnia": "Europe", "Bulgaria": "Europe", "Croatia": "Europe", "Cyprus": "Europe", 
    "Czech Republic": "Europe", "Denmark": "Europe", "England": "Europe", "Estonia": "Europe", 
    "Faroe Islands": "Europe", "Finland": "Europe", "France": "Europe", "Georgia": "Europe", 
    "Germany": "Europe", "Gibraltar": "Europe", "Greece": "Europe", "Hungary": "Europe", 
    "Iceland": "Europe", "Ireland": "Europe", "Israel": "Europe", "Italy": "Europe", 
    "Kosovo": "Europe", "Latvia": "Europe", "Liechtenstein": "Europe", "Lithuania": "Europe",
    "Luxembourg": "Europe", "Malta": "Europe", "Moldova": "Europe", "Montenegro": "Europe",
    "Netherlands": "Europe", "North Macedonia": "Europe", "Northern Ireland": "Europe",
    "Norway": "Europe", "Poland": "Europe", "Portugal": "Europe", "Romania": "Europe",
    "Russia": "Europe", "San Marino": "Europe", "Scotland": "Europe", "Serbia": "Europe", 
    "Slovakia": "Europe", "Slovenia": "Europe", "Spain": "Europe", "Sweden": "Europe", 
    "Switzerland": "Europe", "Turkey": "Europe", "Ukraine": "Europe", "Wales": "Europe",
    
    # All America - North, Central, South America and Caribbean as ONE continent
    "Anguilla": "America", "Antigua and Barbuda": "America", "Aruba": "America", 
    "Bahamas": "America", "Barbados": "America", "Belize": "America", 
    "Bermuda": "America", "British Virgin Islands": "America", "Canada": "America", 
    "Cayman Islands": "America", "Costa Rica": "America", "Cuba": "America",
    "Curaçao": "America", "Dominica": "America", "Dominican Republic": "America", 
    "El Salvador": "America", "Grenada": "America", "Guatemala": "America",
    "Guyana": "America", "Haiti": "America", "Honduras": "America", 
    "Jamaica": "America", "Mexico": "America", "Montserrat": "America",
    "Nicaragua": "America", "Panama": "America", "Puerto Rico": "America", 
    "Saint Kitts and Nevis": "America", "Saint Lucia": "America", 
    "Saint Vincent and the Grenadines": "America", "Suriname": "America", 
    "Trinidad and Tobago": "America", "Turks and Caicos Islands": "America", 
    "United States": "America", "US Virgin Islands": "America", "USA": "America",
    "Argentina": "America", "Bolivia": "America", "Brazil": "America", 
    "Chile": "America", "Colombia": "America", "Ecuador": "America",
    "Paraguay": "America", "Peru": "America", "Uruguay": "America", 
    "Venezuela": "America",
    
    # Oceania countries mapped to Asia
    "American Samoa": "Asia", "Cook Islands": "Asia", "Fiji": "Asia", 
    "New Caledonia": "Asia", "Papua New Guinea": "Asia", "Samoa": "Asia",
    "Solomon Islands": "Asia", "Tahiti": "Asia", "Tonga": "Asia", 
    "Vanuatu": "Asia",
}
SIZES = ["S", "M", "L", "XL","2XL"]
BASE_FOLDER = "test_folder"